### ISSUE TITLE
"Securing Ingresses with Venafi" tutorial contains link to missing manifest

### ISSUE THREAD

**Issue by amcginlay** [cert-manager/website#1063]
See [here](https://cert-manager.io/docs/tutorials/venafi/venafi/#installing-ingress-nginx).

The manifest at https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/provider/aws/service-nlb.yaml is no longer present.

I suspect this needs to be repointed to https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/provider/aws/nlb-with-tls-termination/deploy.yaml but this has not been tested

**Comment by amcginlay** [comment]
Furthermore I think https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/mandatory.yaml should become https://github.com/kubernetes/ingress-nginx/blob/main/deploy/static/provider/aws/deploy.yaml

**Comment by amcginlay** [comment]
Also, in `venafi-issuer.yaml` the attribute `spec.venafi.cloud.url` is no longer required and its inclusion as specified causes a failure.
[This](https://cert-manager.io/docs/configuration/venafi/) documentation has it correct.

**Comment by amcginlay** [comment]
Also, the certificate manifest needs a `commonName` so, for example:
```
spec:
  secretName: demo-jetstack-mcginlay.net-tls
  dnsNames:
  - demo.jetstack.mcginlay.net
  commonName: demo.jetstack.mcginlay.net
```
