### ISSUE TITLE
Clarify what namespace certificates are issued into when using annotations

### ISSUE THREAD

**Issue by loganmarchione** [cert-manager/website#1088]
I've defined a `certificate.yaml` file and successfully requested a certificate from Let's Encrypt using the DNS01 challenge.

```
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: whoami-letsencrypt-production-cert
  namespace: cert-manager
spec:
  commonName: whoami.${SECRET_INTERNAL_DOMAIN_NAME}
  dnsNames:
    - whoami.${SECRET_INTERNAL_DOMAIN_NAME}
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  secretName: whoami-tls
```

I can run the command below and see the certificate.
`kubectl get certificate -n cert-manager`

I've now moved onto creating certificates inside my `Ingress` definitions using [this documentation](https://cert-manager.io/docs/usage/ingress/) and it works successfully.

```
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: drawio-ingress
  namespace: drawio
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  rules:
    - host: drawio.${SECRET_INTERNAL_DOMAIN_NAME}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: drawio-service
                port:
                  number: 8080
  tls:
    - hosts:
        - drawio.${SECRET_INTERNAL_DOMAIN_NAME}
      secretName: drawio-tls
```

But, I don't see the certs when running the command below.
`kubectl get certificate -n cert-manager`

Instead the certificates are in the namespace of the `Ingress`.

```
$ kubectl get certificate -n drawio
NAME         READY   SECRET       AGE
drawio-tls   True    drawio-tls   14m
```

This [documentation](https://cert-manager.io/docs/usage/ingress/#supported-annotations) says:
> `cert-manager.io/cluster-issuer`: the name of a ClusterIssuer to acquire the certificate required for this Ingress. It does not matter which namespace your Ingress resides, as ClusterIssuers are non-namespaced resources.

Can this be clarified to say that the issued certificate will be in the same namespace as the `Ingress`, as opposed to cert-manager's namespace? Something along those lines...
