### ISSUE TITLE
Why the sample issuer still uses kubebuilder version 2 ? 

### ISSUE THREAD

**Issue by djkormo** [cert-manager/website#1159]
https://cert-manager.io/docs/contributing/external-issuers/
The Sample External Issuer is maintained by the cert-manager team, and its README file has step-by-step instructions on how to write an external issuer using Kubebuilder and controller-runtime.

Why the sample issuer still uses kubebuilder version 2 ? 

```
domain: example.com
repo: github.com/cert-manager/sample-external-issuer
resources:
- group: sample-issuer
  kind: Issuer
  version: v1alpha1
- group: sample-issuer
  kind: ClusterIssuer
  version: v1alpha1
version: "2"
```

According to kubebuilder documentation version 2 is treated as a legacy one.
https://book.kubebuilder.io/migration/legacy/v2vsv3.html
