### ISSUE TITLE
Issue reproducing "Securing NGINX-ingress" docs

### ISSUE THREAD

**Issue by augustodsgv** [cert-manager/website#1725]
Hello. I'm studying how to deploy cert-manager in k8s clusters and I had an issue reproducing the docs [Securing NGINX-ingress](https://github.com/cert-manager/website/issues). I'm new here so let me know if I made a mistake or if it's duplicated issue :)

I successfully followed all the steps 1-6 on a brand new cluster until I got stuck on last one [Step 7 - Deploy a TLS Ingress Resource](https://cert-manager.io/docs/tutorials/acme/nginx-ingress/#step-7---deploy-a-tls-ingress-resource), where I've got an error on the challenge, which throws this error:

```
Warning  PresentError  2m3s (x7 over 7m8s)  cert-manager-challenges  Error presenting challenge:  admission webhook "validate.nginx.ingress.kubernetes.io" denied the request: ingress contains invalid paths: path /.well-known/acme-challenge/... cannot be used with  pathType Exact
```
Here follows the yaml files that I created during the process
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuard
spec:
  selector:
    matchLabels:
      app: kuard
  replicas: 1
  template:
    metadata:
      labels:
        app: kuard
    spec:
      containers:
      - image: gcr.io/kuar-demo/kuard-amd64:1
        imagePullPolicy: Always
        name: kuard
        ports:
        - containerPort: 8080
```
```
apiVersion: v1
kind: Service
metadata:
  name: kuard
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: kuard
```
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kuard
  annotations:
    cert-manager.io/issuer: "letsencrypt-staging"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - my-cluster.my-domain.com
    secretName: quickstart-example-tls
  rules:
  - host: my-cluster.my-domain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kuard
            port:
              number: 80
```
```
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: my-email@my-provider.com
    profile: tlsserver
    privateKeySecretRef:
     name: letsencrypt-staging
    solvers:
    - http01:
        ingress:
          ingressClassName: nginx
```
My cert-manager helm chart is cert-manager-v1.18.0   of app version v1.18.0
My nginx helm chart is  ingress-nginx-4.12.3  of app version 1.12.3

Thanks in advance for your help.

**Comment by wallrj** [comment]
There's a bug in the latest version of ingress-nginx which makes it incompatible with the latest version of cert-manager.  You can read about it here, including some work arounds:
 * https://cert-manager.io/docs/releases/release-notes/release-notes-1.18#acme-http01-challenge-paths-now-use-pathtype-exact-in-ingress-routes

Updating this tutorial is on our todo list: 
 * https://github.com/cert-manager/cert-manager/issues/7822

**Comment by augustodsgv** [comment]
Hello @wallrj, thanks for your response.

It makes sense now. I'll try the work around on the docs you sent. 

Thank you and have a nice week.

**Comment by FrancescoD3V** [comment]
Dear @wallrj,
As I mentioned earlier, I have read your documentation, but I honestly didn’t understand how to modify the cert-manager configuration to disable ACMEHTTP01IngressPathTypeExact.
Do I need to run the following command to make this change?

`helm install cert-manager jetstack/cert-manager \
  --namespace cert-manager --create-namespace \
  --values cert-manager-values.yaml
`

Any practical suggestions are welcome, thank you😉

**Comment by yasseraj** [comment]
hello @FrancescoD3V, I followed that documentation, and you are heading right.
This is what worked for me, I reinstalled cert-manager:

helm install cert-manager jetstack/cert-manager --namespace cert-manager --create-namespace --version v1.18.2 --set crds.enabled=true --set crds.keep=true --set global.leaderElection.namespace=cert-manager --set config.featureGates.ACMEHTTP01IngressPathTypeExact=false

**Comment by yasseraj** [comment]
Hello @FrancescoD3V,
I suspect you are redirecting everything to https, hence the url of the challenge that letsencrypt is hitting starts with https, so it gets 308 redirect. I had a similar problem, I have in my nginx annotation to always redirect to https, but to make an exception for acme, I had to add the same annotation as a template inside the cluster issuer  and set the redirect to false. I am not near my laptop, but this is what the solver part looks like in my cluster issuer:

    ```
solvers:
    - http01:
        ingress:
          class: nginx
          podTemplate:
            metadata:
              annotations:
                nginx.ingress.kubernetes.io/ssl-redirect: "false"
```
just a suggestion, if you use dns solvers like cloudflare etc, you won't have this problem at all, because that's API based, but I got things working both ways. I hope that helps.
