### ISSUE TITLE
ACME - Replacing existing account in Kubernetes

### ISSUE THREAD

**Issue by fabio-510** [cert-manager/website#177]
It's not clear in the documentation how to change the account for Let's Encrypt, once it has been assigned.

The scenario is, that given cert-manager has been installed in several Kubernetes clusters, different secret keys get generated automatically for each cert-manager installation. These keys are used to register a new account in Let's Encrypt. The account (and account id) can be verified by inspecting Let's Encrypt ClusterIssuer:

```
#Some lines deleted for clarity

apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: redacted@redacted.com
    privateKeySecretRef:
      key: tls.key
      name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: traefik
status:
  acme:
    lastRegisteredEmail: redacted@redacted.com
    uri: https://acme-v02.api.letsencrypt.org/acme/acct/123456790
  conditions:
  - lastTransitionTime: "2020-01-08T10:53:19Z"
    message: The ACME account was registered with the ACME server
    reason: ACMEAccountRegistered
    status: "True"
    type: Ready
```

Under status we can check the acccount id **123456790:**

```
status:
  acme:
    lastRegisteredEmail: redacted@redacted.com
    uri: https://acme-v02.api.letsencrypt.org/acme/acct/123456790

```

Now, my assumption (based on my research) is that just replacing the secret specified in **privateKeySecretRef**, for the same one across the clusters, should be sufficient to have a single ACME account. However after doing that and trying to force certificate renewal, the account id in status remain unchanged.

Is there something else that should be done? Or should I just ignore this?
Documentation says nothing about this scenario.
