### ISSUE TITLE
Cloudflare permissions using API tokens

### ISSUE THREAD

**Issue by net47** [cert-manager/website#200]
Following up to https://github.com/jetstack/cert-manager/issues/2878, the API token permissions listed at https://cert-manager.io/docs/configuration/acme/dns01/cloudflare/ seems to be wrong. Can you tell me what permissions are needed for the usage of API tokens?

Thanks!

**Comment by sidapa** [comment]
seems like you just need to put the the secret in the cert-manager namespace like:

```
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
type: Opaque
...

```
