### ISSUE TITLE
Specify ingress class for dns01 solver

### ISSUE THREAD

**Issue by InsOpDe** [cert-manager/website#349]
I have following (cluster)issuer
```yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: q@q.q
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: nginx
      - dns01:
#          ingress:
#            class: nginx-internal
          cloudDNS:
            project: example-project
            serviceAccountSecretRef:
              name: clouddns-dns01-solver-svc-acct
              key: key.json
```
I use two ingress classes `nginx` and `nginx-internal` and want to use a `http01`-solver for the former and `dns01`-solver for the latter. Is there a way, as I suggest with the comments, to specify an ingress-class for `dns01` ?
