### ISSUE TITLE
HTTP Validation - no acme stanza

### ISSUE THREAD

**Issue by johngrabner** [cert-manager/website#400]
[tutorial](https://cert-manager.io/docs/tutorials/acme/http-validation/)

`The acme stanza defines the configuration for our ACME challenges. Here we have defined the configuration for our HTTP01 ...`

references something not in example provided

```

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-com
  namespace: default
spec:
  secretName: example-com-tls
  issuerRef:
    name: letsencrypt-staging
  commonName: example.com
  dnsNames:
  - www.example.com
```

I'm guessing this is a remnant of v1beta spec?
