### ISSUE TITLE
SelfSignedIssuer configuration - API reference docs

### ISSUE THREAD

**Issue by chainhead** [cert-manager/website#69]
In the example [Deployment](https://cert-manager.io/docs/configuration/selfsigned/#deployment), the description says this:

> Since the `SelfSigned` `Issuer` requires no dependency on any other resource to be configured, it is the simplest to configure. All that is required is for the `SelfSigned` stanza to be present in the issuers spec.

The YAML used is:

```yaml
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: selfsigning-issuer
  namespace: sandbox
spec:
  selfSigned: {}
```

Therefore, is it safe to assume that, `spec.selfSigned` can be set to `{}`? It is not very clear as described [here](https://cert-manager.io/docs/reference/api-docs/#cert-manager.io/v1alpha2.SelfSignedIssuer).
