### ISSUE TITLE
[HTTP Validation] Adding example for GCLB

### ISSUE THREAD

**Issue by atb00ker** [cert-manager/website#72]
When you are going through the HTTP Validation tutorial on Google Cloud, you will be stuck on certificate status `OrderCreated`.

Although there is a note on the website:

```
If the ingress field is specified,
....
....
This field is useful for the GCLB ingress controller, as well as a number of others, that assign a single public IP address for each ingress resource
.... 
```

It took me a long while to understand GCLB = Google Cloud Load Balancer.

Might I suggest adding an example as  below.

**Note: The example below creates certificates for multiple domains, I think that's a useful additition in the example to consider the creation of http01 certificates for multiple domains.**

---

For using cert-manger on Google cloud, create an ingress, example:

```
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: example-http-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: your-load-balancer-global-ip-name
spec:
  rules:
  - host: dashboard.example.com
    http: &https_rules
      paths:
      - path: /*
        backend:
          serviceName: openwisp-nginx
          servicePort: 80
  - host: controller.example.com
    http: *https_rules
  tls:
  - hosts:
    - dashboard.example.com
    - controller.example.com
    secretName: example-tls-secret
```

After you create the ingress, it will show an error that the `example-tls-secret` doesn't exist, that's an expected error and you can continue to create the `Certificate` and `ClusterIssuer` as below:

```
---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  namespace: default
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: example@example.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            name: example-http-ingress
        selector: {}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  namespace: default
  name: example-tls-crt
spec:
  secretName: example-tls-secret
  renewBefore: 12h
  dnsNames:
  - dashboard.example.com
  - controller.example.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
```
**You may have to wait for some minutes for the certificates to be created and propagated in the Google Cloud Infrasture properly.**

---
Please let me know if this would be seen as a useful addition and I'll be happy to add it. :smile:
